/* Generated By:JJTree&JavaCC: Do not edit this line. FunctionConstants.java */
package tech.deep.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FunctionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Letter = 3;
  /** RegularExpression Id. */
  int EOS = 4;
  /** RegularExpression Id. */
  int Number = 5;
  /** RegularExpression Id. */
  int Digit = 6;
  /** RegularExpression Id. */
  int Int = 7;
  /** RegularExpression Id. */
  int Float = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<Letter>",
    "<EOS>",
    "<Number>",
    "<Digit>",
    "<Int>",
    "<Float>",
  };

}
